# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockergopinath.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_15c0f10d841345ee9e2619e3cc46e194 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ff609c0c6a71410c84ce7475c89df078 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockergopinath.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_15c0f10d841345ee9e2619e3cc46e194 }}/mlapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_40a80124220f4bb18cabb987e1212c02 }}
        images: 'testdockergopinath.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_15c0f10d841345ee9e2619e3cc46e194 }}/mlapp:${{ github.sha }}'